#!/bin/sh
#

# redirect errors to a file in user's home directory if possible

if [ -z "$XDG_CONFIG_HOME" ]; then
  XDG_CONFIG_HOME="$HOME/.config"
fi

statehome=$XDG_STATE_HOME
if [ -z "$XDG_STATE_HOME" ]; then
  statehome="$HOME/.local/state"
fi
statehome="$statehome/X11"
if ! mkdir -m 700 -p "$statehome"; then
  statehome="$HOME"
fi

errfile="$statehome/.xsession-errors"
if ( umask 077 && cp /dev/null "$errfile" 2> /dev/null )
then
  exec > "$errfile" 2>&1
else
  mktemp="/usr/bin/mktemp"
  if [ "x$mktemp" != "x" -a -x "$mktemp" ]
  then
    for errfile in "${TMPDIR-/tmp}/xses-$USER" "/tmp/xses-$USER"
    do
        if ef="$( umask 077 && $mktemp "$errfile.XXXXXX" 2> /dev/null)"
        then
            exec > "$ef" 2>&1
            mv "$ef" "$errfile" 2> /dev/null
            break
        fi
    done
  else
    exec > /dev/null 2>&1
  fi
fi

case $# in
1)
    case $1 in
    failsafe)
        exec /usr/bin/xterm -geometry 80x24-0-0
        ;;
    esac
esac

# The startup script is not intended to have arguments.

if [ -s "$XDG_CONFIG_HOME/X11/Xsession" ]; then
    exec /bin/sh -ls -c "$XDG_CONFIG_HOME/X11/Xsession"
elif [ -s "$HOME/.xsession" ]; then
    exec /bin/sh -ls -c "$HOME/.xsession"
else
    if [ -r "$XDG_CONFIG_HOME/X11/Xresources" ]; then
        /usr/bin/xrdb -load "$XDG_CONFIG_HOME/X11/Xresources"
    elif [ -r "$HOME/.Xresources" ]; then
        /usr/bin/xrdb -load "$HOME/.Xresources"
    fi
    if [ -r "$XDG_CONFIG_HOME/X11/.xinitrc" ]; then
        exec /bin/sh -ls -c "$XDG_CONFIG_HOME/X11/.xinitrc"
    elif [ -r "$HOME/.xinitrc" ]; then
        exec /bin/sh -ls -c "$HOME/.xinitrc"
    else
        exec /bin/sh -l /etc/X11/xinit/xinitrc
    fi
fi
